// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WavePayroll.Data;

namespace WavePayroll.Migrations
{
    [DbContext(typeof(PayrollContext))]
    [Migration("20210402183908_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("WavePayroll.Models.FileUpload.UploadedFile", b =>
                {
                    b.Property<int>("UploadedFileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("HoursWorked")
                        .HasColumnType("REAL");

                    b.Property<char>("JobGroup")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReportID")
                        .HasColumnType("INTEGER");

                    b.HasKey("UploadedFileID");

                    b.ToTable("UploadedFile");
                });
#pragma warning restore 612, 618
        }
    }
}
